version: '3.9'

services:
  rococo-db:
    container_name: rococo-db
    image: mysql:8.1.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - rococo-mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 3s
      retries: 5
      interval: 3s
    ports:
      - 3306:3306
    networks:
      - rococo-network
    dns_search: .

  auth.rococo.docker:
    container_name: auth.rococo.docker
    image: ${PREFIX}/rococo-auth:latest
    ports:
      - 9000:9000
    restart: always
    depends_on:
      rococo-db:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - rococo-network
    dns_search: .

  api.rococo.docker:
    container_name: api.rococo.docker
    image: ${PREFIX}/rococo-api:latest
    ports:
      - 8080:8080
    restart: always
    depends_on:
      auth.rococo.docker:
        condition: service_started
    networks:
      - rococo-network
    dns_search: .

  ui.rococo.docker:
    container_name: ui.rococo.docker
    image: ${PREFIX}/rococo-ui:latest
    ports:
      - 80:80
    restart: always
    depends_on:
      api.rococo.docker:
        condition: service_started
    networks:
      - rococo-network
    dns_search: .

volumes:
  rococo-mysql-data:
    external: true

networks:
  rococo-network:
    driver: bridge
